language: node_js

node_js: 15.12.0


services:
  - docker #容器方式处理下面过程

notifications:
  email: false   # 不发送email通知


# 下面变量以后在写这里，引用规则有问题
# 此处铭感信息存放到Travis后台，其它存放此在env。
# env:
#   global:
#     - APP_IMAGE: vue-feme:latest      #产品镜像名
#     - PROUDCT: mclitao
#     - FORM_REG: index.docker.io       #产品源 docker 仓库
#     - TO_REG: registry.heroku.com     #部署目标 huerku 部署仓库


#JOBS方式 完成 CI/CD任务分包，编译、测试、发布等任务。  
jobs:
  include:
    # -----------------CI--------------------------------------------------------------------
    - stage: 1 unit tests
      script: 
        - echo one

    - stage: 2 unit tests
      script: echo two

    - stage: 3 docker build
      script: 
        - echo two
        - echo "$DOCKER_PASSWORD" | docker login "$FORM_REG" -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t $APP_IMAGE .
        - echo "-- push image to docker hub and heroku pass --"
        - docker tag $PROUDCT/$APP_IMAGE $FORM_REG/$HEROKU_APP/$APP_IMAGE
        - docker images
        - docker push "$FORM_REG/$HEROKU_APP/$APP_IMAGE"
        - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY $TO_REG
        - docker tag $PROUDCT/$APP_IMAGE $FORM_REG/$HEROKU_APP/$APP_IMAGE
        - docker push "$FORM_REG/$HEROKU_APP/$APP_IMAGE"  
      # -----------------CD--------------------------------------------------------------------
    - stage: 4 deploy to Heroku pass staging
        script:
          - skip
          # - echo "Debug --deploy-------------------"
          # - curl https://cli-assets.heroku.com/install.sh | sh                         #install heroku
          # - heroku container:release $APP_IMAGE --app $HEROKU_APP;
        deploy:
          <<: *heroku
          app: $HEROKU_APP
          api_key: HEROKU_AUTH_TOKEN